### ISSUE TITLE
Just enough mobile layout

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#138]
Parent issue to track minum viable mobile site

- [x] #272 menu expand/collapse
- [x] #273 theme switch button
- [x] #274 legend
- [x] #275 'click to edit' notice
- [x] #276 search postcode

Some principles are: 
- aim for fullscreen-feel on map view/edit pages
- slide-in full-height elements where appropriate (where full attention can be temporarily given to the activity: menu navigation, search, building data edit?)
- not too much scrolling in UI if likely to want to head back up/down
  - scrolling fine for text-based pages, sequential forms
