### ISSUE TITLE
UI-UX For category panels

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#285]
From discussions with @polly64 for review with @tomalrussell 

- [ ] Last edit date | When entering edit box shows last edit 
- [ ] Last edit by | When entering edit box shows last edit 
- [x] Copy all | Copies every category  #283 
- [x] Copy some (toggles tick box) | Allows selected categories to be copied 
- [ ] Verification button | Allows user to verify other user data     #305
- [ ] Alert button | Menu as twitter > spam / malicious /   #284

**Comment by tomalrussell** [comment]
Closing - consolidating checklist to #299
