### ISSUE TITLE
UI: Layout and design items

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#297]
Tracking multiple issues 

- [ ] 0. Add data accuracy disclaimer box to main page see #277 
- [x] 1. Change `Use` category label to `Use and Type`closes #265 
- [x] 2. Make `Click buildings for details` button more obvious
- [ ] 3. Add colouring London logo to top of page (move cycling colour logo) 
- [ ] 4. Add colouring London logo to key 
- [ ] 5. Add copyright to bottom of key 
- [x] 6. Make search by postcode box work better (cuts text and overlaps) #276 #268 
- [ ] 7. Test locations for switch theme button, rename to day/night 
- [x] 8. Add data ethics link to site (page exists on WIX) #271 
- [x] 9. Add github link to site/WIX #296 #195 
- [x] 10. Update ownership link on site, points to wrong WIX page #261 #241 
- [ ] 11. Add data accuracy button 
- [ ] 12. Change `Age` category label to `Age and History`. Merge demolitions category into this #266 #208 
- [x] 13. Main text on side bar `View Maps` make font bigger
- [x] 14. Add contributors agreement #317 
- [x] 15. Add privacy policy #323

**Comment by tomalrussell** [comment]
Closing in favour of #399 mega-tracking issue
